### ISSUE TITLE
Coping path results in colored layer w/ no image attribute. 

### ISSUE THREAD

**Issue by IanBellomy** [perrysmotors/copy-framer-code#13]
Have a path. Made exportable. Copying and pasting results in layer w/background color of path and no image attribute. 

[See video here](http://ianbellomy.com/share/CopyIssue.mp4)

**Comment by perrysmotors** [comment]
I think you've found a weird edge case. It looks like the layer you've selected was a rectangle which you have edited to create a triangle. My code tests to see if a layer is a rectangle and creates code accordingly. Even though this layer only has three vertices, Sketch says the layer class is still a rectangle so it is treated as such. If you use the path tool to create the triangle instead then the plugin will generate the code you want. Hope that helps. I'm not actively updating this plugin anymore because you can achieve similar results by copying and pasting into Framer Design Mode and Framer will be releasing Framer X soon which does not use CoffeeScript.

**Comment by IanBellomy** [comment]
Roger on all accounts. Thanks for the response. 

One thing I liked about your approach though was that you could directly grab the origin points of imported assets.
