### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by vTruongHenry** [perrysmotors/copy-framer-code#14]
Hey guys!

First, thank you so much for putting this awesome plugin together for the sketch community! I've been using it for a few years now.

I think with the latest update with Sketch version 66.1, the plugin no longer works.

I work at Disney and I love the plugin for our prototypes!

Any chance you'd be able to fix this? I wish there was a donation box somewhere. I'd pay for this haha

-Henry

**Comment by perrysmotors** [comment]
Hey Henry,

Glad to hear the plugin has been useful. Didn't realise anyone was still using it. 

It's stopped working because Sketch have just removed the legacy scripting API for plugins. I think I might be able to get it working again but I might not be able to get to it immediately.

I'll let you know how I get on.

Cheers,

Giles.

**Comment by perrysmotors** [comment]
Hey Henry. I think I've got it working. It's hard to test because I can't find a download for Framer Classic anymore. Let me know how you get on.
